---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-service
  labels:
    app: grpc-service
spec:
  selector:
    matchLabels:
      app: grpc-service
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-service
    spec:
      containers:
        - command:
            - /grpc-server
          args:
            - --port=12500
          image: danielguo/grpc-helloservice:latest
          imagePullPolicy: IfNotPresent
          name: grpc-server
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-service
spec:
  selector:
    app: grpc-service
  ports:
    - protocol: TCP
      port: 12500
      targetPort: 12500